# Generated by Django 5.0 on 2023-12-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Envio')),
            ],
        ),
    ]
