# Generated by Django 5.0 on 2023-12-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('contact_type', models.IntegerField(choices=[(0, 'Pedido de informacion'), (1, 'Comentarios/Sugerencias'), (2, 'Queja/Reclamo')], verbose_name='Mensaje')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('subscription', models.BooleanField(default=False, verbose_name='Suscribirme a Newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
        ),
    ]
